### PR TITLE
remove old broken IE8 polyfill

### PR DESCRIPTION
**Pull request by coliff**
This no longer works since Google Code has closed and not needed

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by redmunds** [comment]
@coliff Thanks, I missed that.

Are you sure you signed the CLA? The CLA check is failing:

Screen Shot 2019-08-08 at 8 18 41 AM

But that could be due to recent changes to add https support, so let me know if I need to followup with IT.

**Comment by coliff** [comment]
I just re-signed it... can you recheck the CLA?

image

**Comment by redmunds** [comment]
Thanks. Must be something messed up on our end.

**Comment by redmunds** [comment]
Thanks. Must be something messed up on our end.

@stevengill CLA check is failing after user has signed CLA. Is this a known issue? I might have messed up some links in my repo.

**Comment by filmaj** [comment]
Hey y'all,

Fil here from Adobe's Open Source Office. I can confirm that @coliff's signed CLA exists in our database so feel free to proceed. In the mean time I will continue to look into why the CLA Bot has trouble with this. Apologies for that!

**Comment by filmaj** [comment]
Ah there we go. Green!

**Comment by redmunds** [comment]
Thanks.. Sorry for delay -- day job getting in the way :)

**Pull request merged**
